cc_binary(
    name = "is_a_pointer",
    srcs = ["is_a_pointer.cpp"],
)

cc_binary(
    name = "is_int_or_bool",
    srcs = ["is_int_or_bool.cpp"],
)

cc_binary(
    name = "is_real",
    srcs = ["is_real.cpp"],
)

cc_binary(
    name = "my_make_unique",
    srcs = ["my_make_unique.cpp"],
)

cc_binary(
    name = "tmp_factorial",
    srcs = ["tmp_factorial.cpp"],
)
