cc_binary(
    name = "rope_user",
    srcs = ["rope_user.cpp"],
    deps = [
        ":rope",
    ],
)

cc_library(
    name = "rope",
    srcs = ["rope.cpp"],
    hdrs = ["rope.h"],
    deps = [],
)

cc_binary(
    name = "iterator_invalidation",
    srcs = ["iterator_invalidation.cpp"],
)

cc_binary(
    name = "silly_set",
    srcs = ["silly_set.cpp"],
)
