cc_binary(
    name = "nothrow",
    srcs = ["nothrow_exception_guarantee.cpp"],
    deps = [],
)

cc_binary(
    name = "strong",
    srcs = ["strong_exception_guarantee.cpp"],
    deps = [],
)

cc_binary(
    name = "basic",
    srcs = ["basic_exception_guarantee.cpp"],
    deps = [],
)
