cc_library(
    name = "book",
    srcs = ["book.cpp"],
    hdrs = ["book.h"],
    deps = [],
)

cc_binary(
    name = "book_main",
    srcs = ["book_main.cpp"],
    deps = [
        ":book",
    ],
)

cc_library(
    name = "point",
    srcs = ["point.cpp"],
    hdrs = ["point.h"],
    deps = [],
)

cc_binary(
    name = "point_main",
    srcs = ["point_main.cpp"],
    deps = [
        ":point",
    ],
)
