cc_library(
    name = "book",
    srcs = ["book.cpp"],
    hdrs = ["book.h"],
    deps = [],
)

cc_binary(
    name = "book_main",
    srcs = ["book_main.cpp"],
    deps = [
        ":book",
    ],
)
