cc_binary(
    name = "marks",
    srcs = ["marks.cpp"],
)

cc_binary(
    name = "rev",
    srcs = ["rev.cpp"],
)

cc_binary(
    name = "min",
    srcs = ["min.cpp"],
)

cc_binary(
    name = "min_template",
    srcs = ["min_template.cpp"],
)
