cc_library(
    name = "point_wk5",
    srcs = ["point.cpp"],
    hdrs = ["point.h"],
    deps = [],
)

cc_binary(
    name = "point_main_wk5",
    srcs = ["point_main.cpp"],
    deps = [
        ":point_wk5",
    ],
)
